[package]
name = "sowork-rust-test-task"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.52"
clap = { version = "3.0.9", features = ["derive"] }
